name: Artifactory Push Workflow

on:
  #push:
  #pull_request:
  workflow_dispatch:
    

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Print artifact_path
        run: echo triggred workflow using artifactory push
